// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	context "context"

	metrics "github.com/antoniokichaev/go-alert-me/internal/entity/metrics"

	mock "github.com/stretchr/testify/mock"
)

// Keeper is an autogenerated mock type for the Keeper type
type Keeper struct {
	mock.Mock
}

type Keeper_Expecter struct {
	mock *mock.Mock
}

func (_m *Keeper) EXPECT() *Keeper_Expecter {
	return &Keeper_Expecter{mock: &_m.Mock}
}

// AddCounter provides a mock function with given fields: ctx, counter
func (_m *Keeper) AddCounter(ctx context.Context, counter *metrics.Counter) (*metrics.Counter, error) {
	ret := _m.Called(ctx, counter)

	var r0 *metrics.Counter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *metrics.Counter) (*metrics.Counter, error)); ok {
		return rf(ctx, counter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *metrics.Counter) *metrics.Counter); ok {
		r0 = rf(ctx, counter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metrics.Counter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *metrics.Counter) error); ok {
		r1 = rf(ctx, counter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Keeper_AddCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCounter'
type Keeper_AddCounter_Call struct {
	*mock.Call
}

// AddCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - counter *metrics.Counter
func (_e *Keeper_Expecter) AddCounter(ctx interface{}, counter interface{}) *Keeper_AddCounter_Call {
	return &Keeper_AddCounter_Call{Call: _e.mock.On("AddCounter", ctx, counter)}
}

func (_c *Keeper_AddCounter_Call) Run(run func(ctx context.Context, counter *metrics.Counter)) *Keeper_AddCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*metrics.Counter))
	})
	return _c
}

func (_c *Keeper_AddCounter_Call) Return(_a0 *metrics.Counter, _a1 error) *Keeper_AddCounter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Keeper_AddCounter_Call) RunAndReturn(run func(context.Context, *metrics.Counter) (*metrics.Counter, error)) *Keeper_AddCounter_Call {
	_c.Call.Return(run)
	return _c
}

// GetCounter provides a mock function with given fields: ctx, name
func (_m *Keeper) GetCounter(ctx context.Context, name string) (*metrics.Counter, error) {
	ret := _m.Called(ctx, name)

	var r0 *metrics.Counter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*metrics.Counter, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *metrics.Counter); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metrics.Counter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Keeper_GetCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCounter'
type Keeper_GetCounter_Call struct {
	*mock.Call
}

// GetCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Keeper_Expecter) GetCounter(ctx interface{}, name interface{}) *Keeper_GetCounter_Call {
	return &Keeper_GetCounter_Call{Call: _e.mock.On("GetCounter", ctx, name)}
}

func (_c *Keeper_GetCounter_Call) Run(run func(ctx context.Context, name string)) *Keeper_GetCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Keeper_GetCounter_Call) Return(_a0 *metrics.Counter, _a1 error) *Keeper_GetCounter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Keeper_GetCounter_Call) RunAndReturn(run func(context.Context, string) (*metrics.Counter, error)) *Keeper_GetCounter_Call {
	_c.Call.Return(run)
	return _c
}

// GetGauge provides a mock function with given fields: ctx, name
func (_m *Keeper) GetGauge(ctx context.Context, name string) (*metrics.Gauge, error) {
	ret := _m.Called(ctx, name)

	var r0 *metrics.Gauge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*metrics.Gauge, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *metrics.Gauge); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metrics.Gauge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Keeper_GetGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGauge'
type Keeper_GetGauge_Call struct {
	*mock.Call
}

// GetGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Keeper_Expecter) GetGauge(ctx interface{}, name interface{}) *Keeper_GetGauge_Call {
	return &Keeper_GetGauge_Call{Call: _e.mock.On("GetGauge", ctx, name)}
}

func (_c *Keeper_GetGauge_Call) Run(run func(ctx context.Context, name string)) *Keeper_GetGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Keeper_GetGauge_Call) Return(_a0 *metrics.Gauge, _a1 error) *Keeper_GetGauge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Keeper_GetGauge_Call) RunAndReturn(run func(context.Context, string) (*metrics.Gauge, error)) *Keeper_GetGauge_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function with given fields: ctx
func (_m *Keeper) GetMetrics(ctx context.Context) (map[string]string, error) {
	ret := _m.Called(ctx)

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Keeper_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type Keeper_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Keeper_Expecter) GetMetrics(ctx interface{}) *Keeper_GetMetrics_Call {
	return &Keeper_GetMetrics_Call{Call: _e.mock.On("GetMetrics", ctx)}
}

func (_c *Keeper_GetMetrics_Call) Run(run func(ctx context.Context)) *Keeper_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Keeper_GetMetrics_Call) Return(_a0 map[string]string, _a1 error) *Keeper_GetMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Keeper_GetMetrics_Call) RunAndReturn(run func(context.Context) (map[string]string, error)) *Keeper_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// SetGauge provides a mock function with given fields: ctx, gauge
func (_m *Keeper) SetGauge(ctx context.Context, gauge *metrics.Gauge) (*metrics.Gauge, error) {
	ret := _m.Called(ctx, gauge)

	var r0 *metrics.Gauge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *metrics.Gauge) (*metrics.Gauge, error)); ok {
		return rf(ctx, gauge)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *metrics.Gauge) *metrics.Gauge); ok {
		r0 = rf(ctx, gauge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metrics.Gauge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *metrics.Gauge) error); ok {
		r1 = rf(ctx, gauge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Keeper_SetGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGauge'
type Keeper_SetGauge_Call struct {
	*mock.Call
}

// SetGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - gauge *metrics.Gauge
func (_e *Keeper_Expecter) SetGauge(ctx interface{}, gauge interface{}) *Keeper_SetGauge_Call {
	return &Keeper_SetGauge_Call{Call: _e.mock.On("SetGauge", ctx, gauge)}
}

func (_c *Keeper_SetGauge_Call) Run(run func(ctx context.Context, gauge *metrics.Gauge)) *Keeper_SetGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*metrics.Gauge))
	})
	return _c
}

func (_c *Keeper_SetGauge_Call) Return(_a0 *metrics.Gauge, _a1 error) *Keeper_SetGauge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Keeper_SetGauge_Call) RunAndReturn(run func(context.Context, *metrics.Gauge) (*metrics.Gauge, error)) *Keeper_SetGauge_Call {
	_c.Call.Return(run)
	return _c
}

// NewKeeper creates a new instance of Keeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Keeper {
	mock := &Keeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
