// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricRepository is an autogenerated mock type for the MetricRepository type
type MetricRepository struct {
	mock.Mock
}

type MetricRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricRepository) EXPECT() *MetricRepository_Expecter {
	return &MetricRepository_Expecter{mock: &_m.Mock}
}

// AddCounter provides a mock function with given fields: metricName, value
func (_m *MetricRepository) AddCounter(metricName string, value int64) {
	_m.Called(metricName, value)
}

// MetricRepository_AddCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCounter'
type MetricRepository_AddCounter_Call struct {
	*mock.Call
}

// AddCounter is a helper method to define mock.On call
//   - metricName string
//   - value int64
func (_e *MetricRepository_Expecter) AddCounter(metricName interface{}, value interface{}) *MetricRepository_AddCounter_Call {
	return &MetricRepository_AddCounter_Call{Call: _e.mock.On("AddCounter", metricName, value)}
}

func (_c *MetricRepository_AddCounter_Call) Run(run func(metricName string, value int64)) *MetricRepository_AddCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64))
	})
	return _c
}

func (_c *MetricRepository_AddCounter_Call) Return() *MetricRepository_AddCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricRepository_AddCounter_Call) RunAndReturn(run func(string, int64)) *MetricRepository_AddCounter_Call {
	_c.Call.Return(run)
	return _c
}

// SetGauge provides a mock function with given fields: metricName, value
func (_m *MetricRepository) SetGauge(metricName string, value float64) {
	_m.Called(metricName, value)
}

// MetricRepository_SetGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGauge'
type MetricRepository_SetGauge_Call struct {
	*mock.Call
}

// SetGauge is a helper method to define mock.On call
//   - metricName string
//   - value float64
func (_e *MetricRepository_Expecter) SetGauge(metricName interface{}, value interface{}) *MetricRepository_SetGauge_Call {
	return &MetricRepository_SetGauge_Call{Call: _e.mock.On("SetGauge", metricName, value)}
}

func (_c *MetricRepository_SetGauge_Call) Run(run func(metricName string, value float64)) *MetricRepository_SetGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *MetricRepository_SetGauge_Call) Return() *MetricRepository_SetGauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricRepository_SetGauge_Call) RunAndReturn(run func(string, float64)) *MetricRepository_SetGauge_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMetricRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMetricRepository creates a new instance of MetricRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMetricRepository(t mockConstructorTestingTNewMetricRepository) *MetricRepository {
	mock := &MetricRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
